name: Build (macOS)
run-name:  Build (macOS)
on: [push]
jobs:
  prepare-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./ofd "documentation/_ overview.md" -o test1.html
      - uses: actions/upload-artifact@v3
        with:
          name: test1.html
          path: test1.html
          retention-days: 1
  
  build:
    needs: prepare-test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - run: ./build_macos_clang.sh
      
      - run: ./ofd "documentation/_ overview.md" -o test2.html
      - uses: actions/download-artifact@v3
        with:
          name: test1.html
      
      - run: clang -O3 output_test.c -o tester
      - run: ./tester test1.html test2.html
      
      - uses: actions/upload-artifact@v3
        with:
          name: ofd
          path: ofd
          retention-days: 1